from collections import defaultdict
from gtnlplib import constants

theta_hand_original = defaultdict(float,
                         {('worldnews','worldnews'):1.,
                          ('worldnews','news'):.5,
                          ('worldnews','world'):.5,
                          ('science','science'):1.,
                          ('askreddit','askreddit'):1.,
                          ('askreddit','ask'):0.5,
                          ('iama','iama'):1,
                          ('todayilearned','til'):1.,
                          ('todayilearned','todayilearned'):1.,
                          ('iama',constants.OFFSET):0.1,
                         })

# add some more weights to this for deliverable 2.3
theta_hand = defaultdict(float,
                         {('worldnews','worldnews'):1.,
                          ('worldnews','news'):.5,
                          ('worldnews','world'):.5,
                          ('science','science'):1.,
                          ('askreddit','askreddit'):1.,
                          ('askreddit','ask'):0.5,
                          ('iama','iama'):1,
                          ('todayilearned','til'):1.,
                          ('todayilearned','todayilearned'):1.,
                          ('worldnews', 'country'): .7,
                          ('worldnews', 'russia'): .7,
                          ('worldnews', 'china'): .7,
                          ('worldnews', 'public'): .7,
                          ('worldnews', 'military'): .7,
                          ('science', 'research'): .7,
                          ('science', 'study'): .7,
                          ('science', 'brains'): .7,
                          ('science', 'farmer'): .7,
                          ('science', 'human'): .7,
                          ('askreddit', 'post'): .7,
                          ('askreddit', 'thanks'): .7,
                          ('askreddit', '2faskreddit'): .7,
                          ('askreddit', 'moderators'): .7,
                          ('iama',"request"):0.7,
                          ('iama',constants.OFFSET):0.1,
                         })
